# https://github.com/hvr/multi-ghc-travis/blob/master/.travis.yml
language: c

env:
 - CABALVER=1.22 GHCVER=7.10.3
 - CABALVER=1.24 GHCVER=8.0.1

before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install --force-yes cabal-install-$CABALVER ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
 - cabal --version
 - echo "$(ghc --version)"
 - travis_retry cabal update
 # install latest version of deps within sandbox
 - git clone https://github.com/haskell-suite/haskell-src-exts ~/haskell-suite/haskell-src-exts
 - git clone https://github.com/haskell-suite/haskell-names ~/haskell-suite/haskell-names
 - cabal sandbox init
 - cabal sandbox add-source ~/haskell-suite/haskell-src-exts
 - cabal sandbox add-source ~/haskell-suite/haskell-names
 # end
 - cabal install happy
 - cabal install --only-dependencies --enable-tests

script:
 - cabal configure --enable-tests
 - cabal build
 - cabal test
 - cabal sdist
