# https://github.com/hvr/multi-ghc-travis/blob/master/.travis.yml
language: c

env:
 - CABALVER=1.22 GHCVER=7.10.3

before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
 - cabal --version
 - echo "$(ghc --version)"
 - travis_retry cabal update
 - cabal install happy
 - cabal install --only-dependencies --enable-tests

script:
 - cabal configure --enable-tests
 - cabal build
 # - cabal test
 - cabal sdist
